# Generated by Django 6.0 on 2026-01-04 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 4, 11, 2, 30, 83378, tzinfo=datetime.timezone.utc)),
        ),
    ]
